In [1]:
import pandas as pd
import numpy as np
datafile = 'BlackFriday.csv'
df = pd.read_csv(datafile)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 537577 entries, 0 to 537576
Data columns (total 12 columns):
User_ID                       537577 non-null int64
Product_ID                    537577 non-null object
Gender                        537577 non-null object
Age                           537577 non-null object
Occupation                    537577 non-null int64
City_Category                 537577 non-null object
Stay_In_Current_City_Years    537577 non-null object
Marital_Status                537577 non-null int64
Product_Category_1            537577 non-null int64
Product_Category_2            370591 non-null float64
Product_Category_3            164278 non-null float64
Purchase                      537577 non-null int64
dtypes: float64(2), int64(5), object(5)
memory usage: 49.2+ MB

In [2]:
def clean(df):
    df=df.fillna(0)
    df['Gender']=np.where(df['Gender'] == 'F',0,1)
    df['Age'] = np.where(df['Age']=='0-17',0,np.where(df['Age']=='18-25',1,np.where(df['Age']=='26-35',2,np.where(df['Age']=='36-45',3,np.where(df['Age']=='46-50',4,np.where(df['Age']=='51-55',5,6))))))
    df['City_Category'] = np.where(df['City_Category']=='A',0,np.where(df['City_Category']=='B',1,2))
    df['Stay_In_Current_City_Years'] = np.where(df['Stay_In_Current_City_Years'] == '4+',4,np.where(df['Stay_In_Current_City_Years'] =='3',3,np.where(df['Stay_In_Current_City_Years'] =='2',2,np.where(df['Stay_In_Current_City_Years'] =='1',1,0))))
    return df

In [3]:
df = clean(df)
df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,0,0,10,0,2,0,3,0.0,0.0,8370
1,1000001,P00248942,0,0,10,0,2,0,1,6.0,14.0,15200
2,1000001,P00087842,0,0,10,0,2,0,12,0.0,0.0,1422
3,1000001,P00085442,0,0,10,0,2,0,12,14.0,0.0,1057
4,1000002,P00285442,1,6,16,2,4,0,8,0.0,0.0,7969
5,1000003,P00193542,1,2,15,0,3,0,1,2.0,0.0,15227
6,1000004,P00184942,1,4,7,1,2,1,1,8.0,17.0,19215
7,1000004,P00346142,1,4,7,1,2,1,1,15.0,0.0,15854
8,1000004,P0097242,1,4,7,1,2,1,1,16.0,0.0,15686
9,1000005,P00274942,1,2,20,0,1,1,8,0.0,0.0,7871
10,1000005,P00251242,1,2,20,0,1,1,5,11.0,0.0,5254
11,1000005,P00014542,1,2,20,0,1,1,8,0.0,0.0,3957
12,1000005,P00031342,1,2,20,0,1,1,8,0.0,0.0,6073
13,1000005,P00145042,1,2,20,0,1,1,1,2.0,5.0,15665
14,1000006,P00231342,0,5,9,0,1,0,5,8.0,14.0,5378
15,1000006,P00190242,0,5,9,0,1,0,4,5.0,0.0,2079
16,1000006,P0096642,0,5,9,0,1,0,2,3.0,4.0,13055
17,1000006,P00058442,0,5,9,0,1,0,5,14.0,0.0,8851
18,1000007,P00036842,1,3,1,1,1,1,1,14.0,16.0,11788
19,1000008,P00249542,1,2,12,2,4,1,1,5.0,15.0,19614
20,1000008,P00220442,1,2,12,2,4,1,5,14.0,0.0,8584
21,1000008,P00156442,1,2,12,2,4,1,8,0.0,0.0,9872
22,1000008,P00213742,1,2,12,2,4,1,8,0.0,0.0,9743
23,1000008,P00214442,1,2,12,2,4,1,8,0.0,0.0,5982
24,1000008,P00303442,1,2,12,2,4,1,1,8.0,14.0,11927
25,1000009,P00135742,1,2,17,2,0,0,6,8.0,0.0,16662
26,1000009,P00039942,1,2,17,2,0,0,8,0.0,0.0,5887
27,1000009,P00161442,1,2,17,2,0,0,5,14.0,0.0,6973
28,1000009,P00078742,1,2,17,2,0,0,5,8.0,14.0,5391
29,1000010,P00085942,0,3,1,1,4,1,2,4.0,8.0,16352
...,...,...,...,...,...,...,...,...,...,...,...,...
537547,1004733,P00244042,1,1,18,2,1,0,1,2.0,15.0,11543
537548,1004734,P00111042,1,5,1,1,1,1,15,0.0,0.0,20924
537549,1004734,P00345842,1,5,1,1,1,1,2,8.0,14.0,13082
537550,1004735,P00278242,1,4,3,2,3,0,1,0.0,0.0,11658
537551,1004735,P00313442,1,4,3,2,3,0,5,6.0,8.0,6863
537552,1004735,P0098642,1,4,3,2,3,0,6,8.0,0.0,16415
537553,1004735,P00119342,1,4,3,2,3,0,10,13.0,0.0,18526
537554,1004735,P00114042,1,4,3,2,3,0,5,14.0,0.0,7099
537555,1004735,P00135142,1,4,3,2,3,0,13,16.0,0.0,578
537556,1004736,P00194542,1,1,20,0,1,1,8,14.0,0.0,2183
537557,1004736,P00175242,1,1,20,0,1,1,2,0.0,0.0,12724
537558,1004736,P00101942,1,1,20,0,1,1,8,17.0,0.0,7796
537559,1004736,P00109142,1,1,20,0,1,1,8,17.0,0.0,7770
537560,1004736,P00084842,1,1,20,0,1,1,8,16.0,0.0,5940
537561,1004736,P00078142,1,1,20,0,1,1,8,16.0,0.0,7834
537562,1004736,P00146742,1,1,20,0,1,1,1,13.0,14.0,11508
537563,1004736,P00154642,1,1,20,0,1,1,8,0.0,0.0,6074
537564,1004736,P00117442,1,1,20,0,1,1,5,14.0,0.0,7084
537565,1004736,P00051142,1,1,20,0,1,1,8,0.0,0.0,7934
537566,1004736,P00048742,1,1,20,0,1,1,5,0.0,0.0,5350
537567,1004736,P00157542,1,1,20,0,1,1,8,14.0,0.0,1994
537568,1004736,P00250642,1,1,20,0,1,1,11,0.0,0.0,5930
537569,1004736,P00023142,1,1,20,0,1,1,5,14.0,0.0,7042
537570,1004736,P00162442,1,1,20,0,1,1,1,16.0,0.0,15491
537571,1004737,P00221442,1,3,16,2,1,0,1,2.0,5.0,11852
537572,1004737,P00193542,1,3,16,2,1,0,1,2.0,0.0,11664
537573,1004737,P00111142,1,3,16,2,1,0,1,15.0,16.0,19196
537574,1004737,P00345942,1,3,16,2,1,0,8,15.0,0.0,8043
537575,1004737,P00285842,1,3,16,2,1,0,5,0.0,0.0,7172
537576,1004737,P00118242,1,3,16,2,1,0,5,8.0,0.0,6875

In [32]:
def reg_purchase(df):
    from sklearn import linear_model
    from sklearn.model_selection import train_test_split
    train, test = train_test_split(df, test_size = 0.3)
    
    x_train = train.iloc[0:,2:8]
    y_train = train['Purchase']

    x_test = test.iloc[0:,2:8]
    y_test = test['Purchase']

    model = linear_model.LinearRegression()
    model.fit(x_train,y_train)
    
    testing_predictions  = model.predict(x_test)
    return testing_predictions

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

array([9201.58940885, 9912.10874002, 9142.05262793, ..., 8339.21963966,
       9863.96648426, 8927.65466208])

In [10]:
def reg_product_category(df):    
    from sklearn import linear_model
    from sklearn.model_selection import train_test_split
    train2, test2 = train_test_split(df, test_size = 0.3)
    
    x_train2 = train2.iloc[0:,2:8]
    y1_train2,y2_train2, y3_train2 = train2['Product_Category_1'],train2['Product_Category_2'], train2['Product_Category_3']

    x_test2 = test2.iloc[0:,2:8]
    y1_test2, y2_test2, y3_test2 = test2['Product_Category_1'],test2['Product_Category_2'], test2['Product_Category_3']

    model2_1 = linear_model.LinearRegression()
    model2_1.fit(x_train2,y1_train2)

    model2_2 = linear_model.LinearRegression()
    model2_2.fit(x_train2,y2_train2)

    model2_3 = linear_model.LinearRegression()
    model2_3.fit(x_train2,y3_train2)


    testing_predictions_y1  = model2_1.predict(x_test2)
    testing_predictions_y2  = model2_2.predict(x_test2)
    testing_predictions_y3  = model2_3.predict(x_test2)
    
    return (testing_predictions_y1,testing_predictions_y2,testing_predictions_y3)

In [13]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
train2, test2 = train_test_split(df, test_size = 0.3)
train2
x_train2 = train2.iloc[0:,2:8]
x_train2
y1_train2,y2_train2, y3_train2 = train2['Product_Category_1'],train2['Product_Category_2'], train2['Product_Category_3']
y1_train2 

x_test2 = test2.iloc[0:,2:8]
y1_test2, y2_test2, y3_test2 = test2['Product_Category_1'],test2['Product_Category_2'], test2['Product_Category_3']






from sklearn import linear_model
model2_1 = linear_model.LinearRegression()
model2_1.fit(x_train2,y1_train2)

model2_2 = linear_model.LinearRegression()
model2_2.fit(x_train2,y2_train2)

model2_3 = linear_model.LinearRegression()
model2_3.fit(x_train2,y3_train2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
testing_predictions_y1  = model2_1.predict(x_test2)
testing_predictions_y2  = model2_2.predict(x_test2)
testing_predictions_y3  = model2_3.predict(x_test2)
testing_predictions_y3

161274